# example netlify.toml
[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

# [[redirects]]
#   from = "/search"
#   to = "https://api.github.com/users/manolors/repos"
#   status = 200
#   force = true # COMMENT: ensure that we always redirect
#   headers = {X-From = "Netlify", Authorization = "Bearer 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"}